name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Build all
      env:
        DAYS: Day01 Day02
        SHORT_SHA: $($GITHUB_SHA | cut -c1-8)
      run: for f in $DAYS; do docker build . --tag aoc-$F:$SHORT_SHA; done
          
    - name: Build Day04
      working-directory: ./Day04
      run: docker build . --tag aoc-day04:$(date +%s)
