name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6
    - run: echo $SHA
      env: 
        SHA: ${{ steps.short-sha.outputs.sha }}
      
    - name: Build Day01
      working-directory: ./${{ env.DAY }}
      run: docker build . --tag aoc-${{ env.DAY }}:${{ env.SHA }}
      env:
        DAY: "Day01"
        REPO: "$(echo $DAY | awk '{print tolower($0))'"
    
    - name: Build Day02
      working-directory: ./${{ env.DAY }}
      run: docker build . --tag aoc-${{ env.DAY }}:${{ env.SHA }}
      env: 
        DAY: "Day02"
        REPO: "$(echo $DAY | awk '{print tolower($0))'"
      
    - name: Build Day03
      working-directory: ./${{ env.DAY }}
      run: docker build . --tag aoc-${{ env.DAY }}:${{ env.SHA }}
      env: 
        DAY: "Day03"
        REPO: "$(echo $DAY | awk '{print tolower($0))'"
          
    - name: Build Day04
      working-directory: ./${{ env.DAY }}
      run: docker build . --tag aoc-${{ env.DAY }}:${{ env.SHA }}
      env: 
        DAY: "Day04"
        REPO: "$(echo $DAY | awk '{print tolower($0))'"
