name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6
    - run: echo $SHA
      env: 
        SHA: ${{ steps.short-sha.outputs.sha }}
      
    - name: Build all
      env:
        DAYS: Day01 Day02
      run: for f in $DAYS; do docker build . --tag aoc-$f:${{ env.SHA }}; done
          
    - name: Build Day04
      working-directory: ./Day04
      run: docker build . --tag aoc-day04:$(date +%s)
